Biblioteca NumPy
Numpy é uma biblioteca matemática para python

Importando a biblioteca

In [36]:
import numpy as np

Array Python e array Numpy

In [37]:
arrPython = [1,2,3,4]
print(arrPython)
print(arrPython[0])

[1, 2, 3, 4]
1


Array utilizando numpy

In [38]:
arrNumpy = np.array([1,2,3,4])
print(arrNumpy)
print(arrNumpy[0])

[1 2 3 4]
1


np.arange()

In [39]:
#arr = np.arange(1, 10, 1, 'int')
arr = np.arange(1, 10, 1, 'float')
print(arr)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [40]:
arr = np.arange(0, 100, 1, 'int')
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


reshape()
E uma função presente na biblioteca que modifica a forma de uma array existente sem alterar seus dados

In [41]:
arr = np.reshape(arr, (10,10), order='C')
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


Indexação de matriz (tensores)
A indexação de matrizes em numpy é semelhante à indexação de listas em Python. Podendo usar colchetes [] para acessar elementos em uma matriz.

A indexação de uma matriz numpy 2D é feita com base nas linhas e colunas. matriz[linha, coluna] 

In [42]:
arr[0,5]

5

Operações sobre matrizes (tensores)
A biblioteca numpy fornece uma série de operações matemáticas para trabalhar com matrizes, incluindo adição, subtração, multiplicação e divisão.

In [43]:
matriz1 = np.array([[1,2],[3,4]])
matriz2 = np.array([[5,6],[7,8]])

matriz_soma = matriz1 + matriz2

print(matriz_soma)

[[ 6  8]
 [10 12]]


In [44]:
matriz_sub = matriz1 + matriz2
print(matriz_sub)

[[ 6  8]
 [10 12]]


np.sum()
Calcula a soma dos elementos de um array.

In [45]:
arr = np.sum(matriz_soma)
arr

36

np.zeros()
Cria um array de zeros com a forma especificada.

In [46]:
#arr0 = np.zeros((5),'int')
#arr0 = np.zeros((5,2),'int')
arr0 = np.zeros((5,2,4),'int')
arr0

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]])

np.eye()
Cria uma matriz 2D identidade (ou matriz identidade) com a forma especificada.

In [47]:
arr_eye = np.eye(10,10,0, 'int')
arr_eye

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

np.random.rand()
Gera números aleatórios de uma distribuição uniforme no intervalor [0,1] e é uma maneira rápida e eficiente de gerar números aleatórios.

In [48]:
#num = np.random.rand()
num = np.random.rand() * 100
num

43.456799828966886

In [49]:
#arr_num = np.random.rand(3,3)
arr_num = np.random.rand(3,3) * 100
arr_num

array([[60.71322001, 24.2278965 , 50.83350064],
       [54.52903522, 34.94125313, 24.77349681],
       [48.93513569, 59.45350738, 48.94470967]])

np.append()
Adiciona elementos ao final de um array existente.

In [51]:
num = np.random.rand(5)
print(num)

num = np.append(num, 0.3)
print(num)


[0.79598682 0.33102135 0.88590641 0.27200528 0.84358806]
[0.79598682 0.33102135 0.88590641 0.27200528 0.84358806 0.3       ]


np.diff()
Calcula a diferença entre elementos consecutivos de um array.

In [54]:
arr = np.array([1,2,3,5,8,13,21])
diff = np.diff(arr)
diff

array([1, 1, 2, 3, 5, 8])

np.vstack()
Adiciona um array ou sequencia ao final de outro array, empilhando-os verticalmente

np.hstack()
É semelhante mas concatena arrays horizontalmente

In [66]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr3 = np.vstack((arr1,arr2))
print('np.vstack:')
print(f'{arr3}\n')

arr4 = np.hstack((arr1,arr2))
print('np.hstack:')
print(f'{arr4}\n')

np.vstack:
[[1 2 3]
 [4 5 6]]

np.hstack:
[1 2 3 4 5 6]



np.column_stack()
Adiciona um array ou sequencia de array ao final de outro array, empilhando-os em colunas.

In [71]:
arr_column_stack = np.column_stack((arr1,arr2))
print(arr_column_stack)

[[1 4]
 [2 5]
 [3 6]]
